version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
